version: '2'
services:
  app:
    build: ./app
    ports:
      - '3000:3000'
    depends_on:
      - server
  server:
    build: ./server
    ports:
      - '4000:4000'
    environment: 
    - POSTGRES_HOST=${POSTGRES_HOST}
    - POSTGRES_PORT=${POSTGRES_PORT}
    - POSTGRES_DB=${POSTGRES_DB}
    - POSTGRES_USER=${POSTGRES_USER}
    - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    - FIREBASE_PRIVATE_KEY="${FIREBASE_PRIVATE_KEY}"
    - FIREBASE_PRIVATE_KEY_ID="${FIREBASE_PRIVATE_KEY_ID}"
    - FIREBASE_CLIENT_ID="${FIREBASE_CLIENT_ID}"